/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mossgrabers_reaper_MainApp */

#ifndef _Included_de_mossgrabers_reaper_MainApp
#define _Included_de_mossgrabers_reaper_MainApp
#ifdef __cplusplus
extern "C" {
#endif
#undef de_mossgrabers_reaper_MainApp_DEVICE_UPDATE_RATE
#define de_mossgrabers_reaper_MainApp_DEVICE_UPDATE_RATE 30L
/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processNoArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processNoArg
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processStringArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processStringArg
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processStringArgs
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processStringArgs
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processIntArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processIntArg
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processDoubleArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processDoubleArg
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    delayUpdates
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_delayUpdates
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    enableUpdates
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_enableUpdates
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processMidiArg
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processMidiArg
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
