/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mossgrabers_reaper_ui_MainFrame */

#ifndef _Included_de_mossgrabers_reaper_ui_MainFrame
#define _Included_de_mossgrabers_reaper_ui_MainFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_DEFAULT
#define de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_SET
#define de_mossgrabers_reaper_ui_MainFrame_FOCUS_TRAVERSABLE_SET 2L
#undef de_mossgrabers_reaper_ui_MainFrame_TOP_ALIGNMENT
#define de_mossgrabers_reaper_ui_MainFrame_TOP_ALIGNMENT 0.0f
#undef de_mossgrabers_reaper_ui_MainFrame_CENTER_ALIGNMENT
#define de_mossgrabers_reaper_ui_MainFrame_CENTER_ALIGNMENT 0.5f
#undef de_mossgrabers_reaper_ui_MainFrame_BOTTOM_ALIGNMENT
#define de_mossgrabers_reaper_ui_MainFrame_BOTTOM_ALIGNMENT 1.0f
#undef de_mossgrabers_reaper_ui_MainFrame_LEFT_ALIGNMENT
#define de_mossgrabers_reaper_ui_MainFrame_LEFT_ALIGNMENT 0.0f
#undef de_mossgrabers_reaper_ui_MainFrame_RIGHT_ALIGNMENT
#define de_mossgrabers_reaper_ui_MainFrame_RIGHT_ALIGNMENT 1.0f
#undef de_mossgrabers_reaper_ui_MainFrame_serialVersionUID
#define de_mossgrabers_reaper_ui_MainFrame_serialVersionUID -7644114512714619750i64
#undef de_mossgrabers_reaper_ui_MainFrame_serialVersionUID
#define de_mossgrabers_reaper_ui_MainFrame_serialVersionUID 4613797578919906343i64
#undef de_mossgrabers_reaper_ui_MainFrame_INCLUDE_SELF
#define de_mossgrabers_reaper_ui_MainFrame_INCLUDE_SELF 1L
#undef de_mossgrabers_reaper_ui_MainFrame_SEARCH_HEAVYWEIGHTS
#define de_mossgrabers_reaper_ui_MainFrame_SEARCH_HEAVYWEIGHTS 1L
#undef de_mossgrabers_reaper_ui_MainFrame_OPENED
#define de_mossgrabers_reaper_ui_MainFrame_OPENED 1L
#undef de_mossgrabers_reaper_ui_MainFrame_serialVersionUID
#define de_mossgrabers_reaper_ui_MainFrame_serialVersionUID 4497834738069338734i64
#undef de_mossgrabers_reaper_ui_MainFrame_DEFAULT_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_DEFAULT_CURSOR 0L
#undef de_mossgrabers_reaper_ui_MainFrame_CROSSHAIR_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_CROSSHAIR_CURSOR 1L
#undef de_mossgrabers_reaper_ui_MainFrame_TEXT_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_TEXT_CURSOR 2L
#undef de_mossgrabers_reaper_ui_MainFrame_WAIT_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_WAIT_CURSOR 3L
#undef de_mossgrabers_reaper_ui_MainFrame_SW_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_SW_RESIZE_CURSOR 4L
#undef de_mossgrabers_reaper_ui_MainFrame_SE_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_SE_RESIZE_CURSOR 5L
#undef de_mossgrabers_reaper_ui_MainFrame_NW_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_NW_RESIZE_CURSOR 6L
#undef de_mossgrabers_reaper_ui_MainFrame_NE_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_NE_RESIZE_CURSOR 7L
#undef de_mossgrabers_reaper_ui_MainFrame_N_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_N_RESIZE_CURSOR 8L
#undef de_mossgrabers_reaper_ui_MainFrame_S_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_S_RESIZE_CURSOR 9L
#undef de_mossgrabers_reaper_ui_MainFrame_W_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_W_RESIZE_CURSOR 10L
#undef de_mossgrabers_reaper_ui_MainFrame_E_RESIZE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_E_RESIZE_CURSOR 11L
#undef de_mossgrabers_reaper_ui_MainFrame_HAND_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_HAND_CURSOR 12L
#undef de_mossgrabers_reaper_ui_MainFrame_MOVE_CURSOR
#define de_mossgrabers_reaper_ui_MainFrame_MOVE_CURSOR 13L
#undef de_mossgrabers_reaper_ui_MainFrame_NORMAL
#define de_mossgrabers_reaper_ui_MainFrame_NORMAL 0L
#undef de_mossgrabers_reaper_ui_MainFrame_ICONIFIED
#define de_mossgrabers_reaper_ui_MainFrame_ICONIFIED 1L
#undef de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_HORIZ
#define de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_HORIZ 2L
#undef de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_VERT
#define de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_VERT 4L
#undef de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_BOTH
#define de_mossgrabers_reaper_ui_MainFrame_MAXIMIZED_BOTH 6L
#undef de_mossgrabers_reaper_ui_MainFrame_serialVersionUID
#define de_mossgrabers_reaper_ui_MainFrame_serialVersionUID 2673458971256075116i64
#undef de_mossgrabers_reaper_ui_MainFrame_serialVersionUID
#define de_mossgrabers_reaper_ui_MainFrame_serialVersionUID 4251131641194938848i64
#undef de_mossgrabers_reaper_ui_MainFrame_GAP
#define de_mossgrabers_reaper_ui_MainFrame_GAP 14L
/*
 * Class:     de_mossgrabers_reaper_ui_MainFrame
 * Method:    processNoArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_ui_MainFrame_processNoArg
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_ui_MainFrame
 * Method:    processStringArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_ui_MainFrame_processStringArg
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_ui_MainFrame
 * Method:    processIntArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_ui_MainFrame_processIntArg
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     de_mossgrabers_reaper_ui_MainFrame
 * Method:    processDoubleArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_ui_MainFrame_processDoubleArg
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     de_mossgrabers_reaper_ui_MainFrame
 * Method:    processMidiArg
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_ui_MainFrame_processMidiArg
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
