/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mossgrabers_transformator_TransformatorApplication */

#ifndef _Included_de_mossgrabers_transformator_TransformatorApplication
#define _Included_de_mossgrabers_transformator_TransformatorApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_mossgrabers_transformator_TransformatorApplication
 * Method:    receiveModelData
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_mossgrabers_transformator_TransformatorApplication_receiveModelData
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_mossgrabers_transformator_TransformatorApplication
 * Method:    processNoArg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_transformator_TransformatorApplication_processNoArg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_mossgrabers_transformator_TransformatorApplication
 * Method:    processStringArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_transformator_TransformatorApplication_processStringArg
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_mossgrabers_transformator_TransformatorApplication
 * Method:    processIntArg
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_transformator_TransformatorApplication_processIntArg
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     de_mossgrabers_transformator_TransformatorApplication
 * Method:    processDoubleArg
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_transformator_TransformatorApplication_processDoubleArg
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
