name: CMake

on:
  push:
    branches: [ master ]
  # Necessary to manually run the workflow
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: reaper_drivenbymoss.so
          - os: macos-11
            artifact_name: reaper_drivenbymoss.dylib
          - os: windows-2019
            artifact_name: reaper_drivenbymoss.dll
    
    name: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Configure CMake
      run: cmake -S "CMake" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --verbose --config ${{env.BUILD_TYPE}}

    - name: Publish result
      uses: actions/upload-artifact@v3
      with:
        name: DrivenByMoss4Reaper-Libraries
        path: ${{github.workspace}}/build/x64/Release/${{ matrix.artifact_name }}
